// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(document).ready(function() {
    return console.log("SASS Boilerplate - ready for action");
  });

}).call(this);

//# sourceMappingURL=main.map
